services:
  postgres:
    image: postgres:17
    container_name: soft-board-postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - soft-board-network

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: soft-board-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - soft-board-network

networks:
  soft-board-network:

volumes:
  soft-board-volume:
